name: Rust CI

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Check if tests passed
      if: ${{ failure() }}
      run: |
        echo "Tests failed! Push rejected."
        exit 1
